### ISSUE TITLE
本地开发运行报错

### ISSUE THREAD

**Issue by MutouLee** [eryajf/chatgpt-dingtalk#108]
```sh
go run main.go 
go: downloading github.com/go-resty/resty/v2 v2.7.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/patrickmn/go-cache v2.1.0+incompatible
go: downloading github.com/avast/retry-go v2.7.0+incompatible
go: downloading github.com/sashabaranov/go-openai v1.5.3
go: downloading golang.org/x/net v0.0.0-20211029224645-99673261e6eb
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/eryajf/chatgpt-dingtalk/public.GetBalance()
	/root/chatgpt-dingtalk/public/gpt.go:47 +0x6c9
github.com/eryajf/chatgpt-dingtalk/public.InitSvc()
	/root/chatgpt-dingtalk/public/public.go:18 +0xea
main.init.0()
	/root/chatgpt-dingtalk/main.go:16 +0x17
exit status 2
```

能帮我看下啥问题么？

切换了CentOS7/8， Ubuntu22.04都是同样的错误。

**Comment by eryajf** [comment]
错误原因：这是项目启动的时候，会先获取一下key对应的余额，然后放到内存里边，这个错误是获取失败了。

排查思路：
- 确认下主机环境到api.openai.com是否通
- 确认配置文件是否正确配置，config.json

大概就这两个因素了。

**Comment by MutouLee** [comment]
> 错误原因：这是项目启动的时候，会先获取一下key对应的余额，然后放到内存里边，这个错误是获取失败了。
> 
> 排查思路：
> 
> * 确认下主机环境到api.openai.com是否通
> * 确认配置文件是否正确配置，config.json
> 
> 大概就这两个因素了。

谢谢，问题找到了，config里面配的key写错了

**Comment by zgz682000** [comment]
我也发生了这个问题，key没问题，openai.com能通，余额接口返回空数组
```
{
  "object": "credit_summary",
  "total_granted": 0.0,
  "total_used": 0.0,
  "total_available": 0.0,
  "grants": {
    "object": "list",
    "data": []
  }
}
```
