### ISSUE TITLE
余额指令无响应，日志报错

### ISSUE THREAD

**Issue by Yveeven** [eryajf/chatgpt-dingtalk#156]
## 问题反馈

使用余额指令时无响应，查询日志报错如下

![image](https://user-images.githubusercontent.com/76424723/229312775-1de91f41-927f-43a9-9ed9-896bb275e6c0.png)

**Comment by eryajf** [comment]
这两天官方的余额接口有点问题，可先忽略

**Comment by gltjk** [comment]
> 这两天官方的余额接口有点问题，可先忽略

我这边启动的时候就直接报了错，然后就终止了😂

```text
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/eryajf/chatgpt-dingtalk/public.GetBalance()
        /github/workspace/public/balance.go:51 +0x729
github.com/eryajf/chatgpt-dingtalk/public.InitSvc()
        /github/workspace/public/public.go:23 +0x147
main.init.0()
        /github/workspace/main.go:21 +0x17
```

**Comment by 10cks** [comment]
同样的问题，报错就终止了

**Comment by eryajf** [comment]
这个我来兼容一下

**Comment by arthurain** [comment]
> 这个我来兼容一下

我也是这个问题，跑了好几天很稳定，忽然今天就不行了，查了一个docker log，一样的情况
